apiVersion: apps/v1
kind: Deployment
metadata:
  name: wedding-planner-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wedding-planner
  template:
    metadata:
      labels:
        app: wedding-planner
    spec:
      containers:
      - name: wedding-planner-container
        image: gahana15/wedding-planner:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: wedding-planner-service
spec:
  type: LoadBalancer
  selector:
    app: wedding-planner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
